### ISSUE TITLE
有没有什么方法限制帧数

### ISSUE THREAD

**Issue by Kapsugar** [LoveBeforT/WarcraftHelper#10]
问一下大佬，有没有什么办法能锁帧，现在帧数是没有上限的，我想锁个75或者144，应该改什么地方呢？

**Comment by LoveBeforT** [comment]
几种思路：
1. 在显卡控制面板里面设置魔兽的fps上限。
2. 在注册表中改魔兽的maxfps。
3. 使用窗口化玩魔兽，需要注意的是A卡和N卡情况稍有不同，有的显卡窗口化后fps就自动限制在屏幕刷新率了，我之前RX6600和RTX3060遇到过这种区别。

一般来讲，第一种显卡驱动里面设置最大fps是最有效的

**Comment by LoveBeforT** [comment]
![image](https://user-images.githubusercontent.com/13610008/190633237-30b3586f-edd9-447f-ac6b-9502e6372b62.png)
![image](https://user-images.githubusercontent.com/13610008/190633398-89b33aea-fd2a-4774-a9cb-1ad085a0ad96.png)
如图，我在N卡驱动这里设置144帧率，游戏里就只有144fps了。平时的话我RTX3060能有400+fps

**Comment by Kapsugar** [comment]
好的，谢谢。
