### ISSUE TITLE
huiyuhuiyi你再骚扰我，我就拜访你全家！

### ISSUE THREAD

**Issue by dq11dq11** [LoveBeforT/WarcraftHelper#20]
huiyuhuiyi你再骚扰我，我就拜访你全家！

**Comment by huiyuhuiyi** [comment]
意义呢? 譬如1080P  情况下, 显卡也就只能工作到120-80fps左右,  你显示1000FPS 有什么用?

**Comment by dq11dq11** [comment]
你的显卡只显示到80-120fps？这么垃圾？

**Comment by huiyuhuiyi** [comment]
楼主好逗,   1080p  gtx 1660,  80-120fps 是正常,  2560*1440,  2.5k  gtx 2060, 100fps 也是正常,  2.5k ＞ 150fps 起码要上3系列以上
楼主扯蛋1000fps ,就想问问你家是什么显卡

**Comment by dq11dq11** [comment]
RTX3060

**Comment by dq11dq11** [comment]
你歌姬吧没用过rtx3060开过1000帧就说人扯蛋，你不是井底之蛙？

**Comment by dq11dq11** [comment]
再说你说gtx 1660 gtx 2060没超过1000帧你没说证据图片，老黄说过了吗，以前ps1时代ps2时代windows95 98游戏没有超过30帧，现在有60帧，120帧，144帧，240帧，不代表以后没有1000帧，以前只有cpu，没有显卡，现在有显卡，而且越来越大，大到机箱都放不进去那个rtx4090,而且支持分辩率从320x240增加到可怕的8k分辨率，以前crt电视，现在液晶led电视，高亮度鲜艳但寿命短的oled电视，更高亮度鲜艳寿命长但成本昂贵的micro led电视 ,高亮度鲜艳寿命长成本低的mini led电视，时代是在进步的，以前超大张的LD到容量变大犳cd到可以同时储存音频视频的国产高光的vcd再到盗版遍地的DVD，然后是BD，然后是超大容量的4K UHD BD。以前游戏只有黑白几kb到现在steam游戏动则几十gb或更高达到100GB，你想过没有？你要学会适应这个社会不然被淘汰！已经有人证明可以1000帧：https://tieba.baidu.com/p/7069257012?pn=1 这个是我提高1000帧的魔兽争霸3

**Comment by dq11dq11** [comment]
https://www.bilibili.com/video/BV1Fo4y1v7xN/

**Comment by huiyuhuiyi** [comment]
另外忘记跟楼主说了, 就算给你真的软改到1000FPS, 也即使显示卡真实可以渲染1000FPS, 我就问问你, 你知道什么叫做显示器刷新率吗?   我这台电脑的显示器 是最新 240刷新率的, 再往上的fps , 也会被显示器的刷新率所局限, 原来楼主的显示器是1000刷新率, 哦, 火星科技, 不错不错

**Comment by huiyuhuiyi** [comment]
1920*1080P  240刷新率,  27英寸是折衷配套玩war3, 因为我现在用的线材是 HDMI2.0,   如果换成27英寸 2.5k (2560*1440), 是做不到240刷新率 (基于我现有购买的显示器), 而且线材带宽也不足 需要换HDMI 2.1版本,  但我实际使用的显卡是GTX 1660, 因此在1920*1080P  27英寸来讲, 足够了, 如果换成 27英寸2.5k (2560*1440), 显示器, fps还会降低, 刷新率也低,   楼主吹牛逼半天, 完全忽视显示器支撑的刷新率, 以及线材支持,   你1000FPS, 需要配一个1000多刷新率的显示器, 要不然屁用都没, 再者 线材带宽也必须跟的上, 说了半天, 楼主可以总结为:  吹牛逼我第一,

**Comment by dq11dq11** [comment]
如果哪一天真有1000HZ的显示器出现，你给我直播倒立吃屎！

**Comment by dq11dq11** [comment]
你只会阻碍社会进步，阻碍科技发展，你肯可能是一个反社会人格的极端分子，我总结你为：人渣！

**Comment by dq11dq11** [comment]
你不要再骚扰我，否则我动用人际关系找到你并将你处理掉！
